f=open("Mad-LibResult.txt","w")
player = input ("What is your name?")
print ("Welcome %s to my interactive fill in the blank experience, otherwise known as a mad-lib" % (player))

place1=input ("Name a place")
name1=input ("Enter a name")
verb1=input ("Enter a present tense verb")
place2=input ("Name another place")
restaurant1=input ("Enter your third favorite restaurant")
place3=input ("Name a type of civilization")
animal1=input ("Enter a type of large animal")
emotion1=input ("Enter an emotion")
verb2=input ("Enter an enjoyable activity")

output= """Once upon a time in the magical land of %s, there was a prince named %s who loved to %s.""" %(place1,name1,verb1)
output2= """One day, after going to %s with some friends %s decided to take them all to %s,""" %(place2,name1,restaurant1)
output3= """which as chance would have it a travelling circus was passing through the %s and a(n) %s destroyed %s."""%(place3,animal1,restaurant1)
output4= """But rather than be %s, they decided to go %s instead.""" %(emotion1,verb2)
print (output,output2,output3,output4)
f.write(output + "\n")
f.write(output2 +"\n")
f.write(output3 +"\n")
f.write(output4)
f.close()

